### ISSUE TITLE
error : too many argument to function 'netif_napi_add'
netif_napi_add(ndev, &adapter->napi, rtw_recv_napi_poll, RTL_NAPI_WEIGHT);

### ISSUE THREAD

**Issue by Adex-23** [fastoe/RTL8811CU#3]
please help me fix this

**Comment by Astatin3** [comment]
I'm pretty sure this is due to this being built for an older version of the Linux kernel, someone has already gone and updated this for version >= 6, and it's in a pull request. I have no idea why this hasn't been approved yet

I was successfully able to build this with debian 6.1.0-13-amd64

https://github.com/alex14fr/RTL8811CU

( Thank you so much @alex14fr  )
